# Generated by Django 4.2.10 on 2024-02-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date published',
            new_name='pub_date',
        ),
    ]
